server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SturnioloBruno/parcial-Back-esp
          default-label: develop
          force-pull: true
          search-paths: configData
