version: '3.3'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'movie-dev'
      MYSQL_USER: 'usr-movie'
      MYSQL_PASSWORD: 'pwd-movie'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
  # mongodb:
  #   image: mongo
  #   container_name: "mongodb"
  #   command: mongod --auth
  #   environment:
  #     - MONGO_INITDB_DATABASE=admin
  #     - MONGO_INITDB_ROOT_USERNAME=rootuser
  #     - MONGO_INITDB_ROOT_PASSWORD=rootpass
  #   ports:
  #     - "27017:27017"
  #   expose:
  #     - 27017
  #   volumes:
  #     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
