server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-serie
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: tp_final
      port: 27017
      host: mongodb

  zipkin:
    base-url: http://localhost:9411
    enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka

